### ISSUE TITLE
PermissionError on lgl run

### ISSUE THREAD

**Issue by Nancy12717** [libgirlenterprise/lgl#16]
When execute `lgl run` on [lgl_target_project](https://github.com/libgirlenterprise/lgl_target_project), it happens to a PermissionError: 

`PS C:\Users\kevin-tsai\Desktop\lgl_target_project> lgl run lgl_live_demo/lgl_live_demo.py
Traceback (most recent call last):
  File "c:\users\kevin-tsai\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kevin-tsai\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kevin-tsai\Miniconda3\Scripts\lgl.exe\__main__.py", line 9, in <module>
  File "c:\users\kevin-tsai\miniconda3\lib\site-packages\lgl\lgl.py", line 60, in main
    args.handler(args)
  File "c:\users\kevin-tsai\miniconda3\lib\site-packages\lgl\lgl.py", line 12, in command_run
    lgl.install_module(["./"])
  File "c:\users\kevin-tsai\miniconda3\lib\site-packages\lgl\__init__.py", line 44, in install_module
    result=result+list_unresolved(file)
  File "c:\users\kevin-tsai\miniconda3\lib\site-packages\lgl\__init__.py", line 25, in list_unresolved
    return get_unresolve.list_unresolved(path)
  File "c:\users\kevin-tsai\miniconda3\lib\site-packages\lgl\get_unresolve.py", line 9, in list_unresolved
    with open(path) as f:
PermissionError: [Errno 13] Permission denied: './'`

OS : Windows

**Comment by cataska** [comment]
Try to run it as administrator.

**Comment by snmsts** [comment]
fixed with 209e191
